using System;

namespace Reference.Domain.Attributes
{
    /// <summary>
    /// Mark an entity with this attribute to avoid defining DbSets in the generated DbContext (use if the tables are generated by some other means, e.g. ASP.NET Identity.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false)]
    internal class SkipTableAttribute : Attribute
    {

    }
}